INSERT INTO PAIS VALUES(1, 'BRASIL', 'BR');
INSERT INTO PAIS VALUES(2, 'ARGENTINA', 'AR');
INSERT INTO PAIS VALUES(3, 'ALEMANHA', 'DE');
INSERT INTO PAIS VALUES(4, 'EMIRADOS ÁRABES', 'EA');



INSERT INTO ESTADO VALUES(10, 'RIO GRANDE DO SUL', 'RS', 1);
INSERT INTO ESTADO VALUES(11, 'SANTA CATARINA', 'SC', 1);
INSERT INTO ESTADO VALUES(12, 'BAHIA', 'BA', 1);
INSERT INTO ESTADO VALUES(13, 'CHEMNITZ', 'CH', 3);
INSERT INTO ESTADO VALUES(14, 'BUENOS AIRES', 'BA', 2);