CREATE TABLE FILME (
  ID NUMBER PRIMARY KEY NOT NULL,
  TITULO VARCHAR2(50) NOT NULL,
  LANCAMENTO DATE NOT NULL,
  CATEGORIA VARCHAR2(50)
  );
  
  CREATE SEQUENCE S_FILME;
  SELECT * FROM FILME;
  DROP TABLE FILME;
  
  CREATE TABLE CLIENTE (
    ID NUMBER PRIMARY KEY NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    TELEFONE NUMBER NOT NULL,
    ENDERECO VARCHAR2(100) NOT NULL
    );
    
    CREATE SEQUENCE S_CLIENTE;
    SELECT * FROM CLIENTE;
    DROP TABLE CLIENTE;
    
CREATE TABLE ALUGUEL (
  ID NUMBER PRIMARY KEY NOT NULL,
  RETIRADA DATE NOT NULL,
  PREVISAO DATE NOT NULL,
  DEVOLUCAO DATE,
  MULTA FLOAT,
  ID_CLIENTE NOT NULL REFERENCES CLIENTE (ID)
  );
 
  CREATE SEQUENCE S_ALUGUEL;
  SELECT * FROM ALUGUEL;
 
  
CREATE TABLE MIDIA (
    ID NUMBER PRIMARY KEY NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    ID_FILME NOT NULL REFERENCES FILME (ID),
    ID_ALUGUEL REFERENCES ALUGUEL (ID)
    );
    
CREATE SEQUENCE S_MIDIA;
SELECT * FROM MIDIA;


CREATE TABLE VALOR_MIDIA (
  ID NUMBER PRIMARY KEY NOT NULL,
  VALOR FLOAT NOT NULL,
  INICIO_VIGENCIA DATE NOT NULL,
  FIM_VIGENCIA DATE,
  ID_MIDIA NOT NULL REFERENCES MIDIA(ID)
  );

  CREATE SEQUENCE S_VALOR_MIDIA;
  SELECT * FROM VALOR_MIDIA;
  
  
  
  
  
  DROP TABLE MIDIA;
  DROP TABLE VALOR_MIDIA;
  DROP TABLE ALUGUEL;
  DROP TABLE CLIENTE;
  DROP TABLE FILME;
  
  DROP SEQUENCE S_VALOR_MIDIA;
  DROP SEQUENCE S_MIDIA;
  DROP SEQUENCE S_ALUGUEL;
  DROP SEQUENCE S_CLIENTE;
  DROP SEQUENCE S_FILME;
  
  COMMIT;

